
version: "3"
services:

  postgres-application:
    image: postgres
    container_name: postgres-application
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT_OUT}:${POSTGRES_PORT_IN}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  # application: 
  #   container_name: application
  #   build: 
  #     context: ../education
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #    - postgres-application
  #   restart: unless-stopped

volumes:
  pgdata: